"""crear_tablas_iniciales

Revision ID: fbed4e566f42
Revises: 
Create Date: 2026-06-27 20:16:05.038200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbed4e566f42'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Especialidad',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Nombre', sa.String(length=80), nullable=False),
    sa.Column('Activa', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Nombre')
    )
    op.create_table('Actividad',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('EspecialidadId', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(length=100), nullable=False),
    sa.Column('Activa', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['EspecialidadId'], ['Especialidad.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Complemento_Parte_Diario',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('AgendamientoId', sa.Integer(), nullable=False),
    sa.Column('MedicoId', sa.Integer(), nullable=False),
    sa.Column('FechaParte', sa.Date(), nullable=False),
    sa.Column('EspecialidadId', sa.Integer(), nullable=False),
    sa.Column('ActividadId', sa.Integer(), nullable=False),
    sa.Column('TipoConsulta', sa.String(length=15), nullable=False),
    sa.Column('Pre_QT', sa.Boolean(), nullable=False),
    sa.Column('Pre_QX', sa.Boolean(), nullable=False),
    sa.Column('Quimio', sa.Boolean(), nullable=False),
    sa.Column('EKG', sa.Boolean(), nullable=False),
    sa.Column('CreadoEn', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ActualizadoEn', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('CreadoPor', sa.Integer(), nullable=False),
    sa.CheckConstraint("TipoConsulta IN ('PRIMERA_VEZ', 'SUBSECUENTE')", name='ck_tipo_consulta'),
    sa.ForeignKeyConstraint(['ActividadId'], ['Actividad.Id'], ),
    sa.ForeignKeyConstraint(['EspecialidadId'], ['Especialidad.Id'], ),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('AgendamientoId', name='uq_agendamiento')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Complemento_Parte_Diario')
    op.drop_table('Actividad')
    op.drop_table('Especialidad')
    # ### end Alembic commands ###
